<?php

declare(strict_types=1);

require_once __DIR__ . '/../../../vendor/autoload.php';
require_once __DIR__ . '/daycard-locks-common.php';

use Dompdf\Dompdf;
use Dompdf\Options;

reconDaycardLocksBoot();
if (empty($_SESSION['user'])) {
    http_response_code(401);
    exit('Unauthorized');
}

$payload = reconDaycardLocksReadPayload();
$partner = trim((string) ($payload['partner'] ?? ''));
$startDate = reconDaycardLocksNormalizeDate((string) ($payload['start_date'] ?? ''));
$endDate = reconDaycardLocksNormalizeDate((string) ($payload['end_date'] ?? ''));
$statusFilter = trim((string) ($payload['status_filter'] ?? 'All Status'));
$rows = is_array($payload['rows'] ?? null) ? $payload['rows'] : [];

if ($partner === '' || $startDate === '' || $endDate === '' || count($rows) > 366) {
    http_response_code(400);
    exit('Invalid export data.');
}

$escape = static fn (string $value): string => htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
$formatDate = static function (string $value): string {
    $date = DateTimeImmutable::createFromFormat('Y-m-d', $value);
    return $date ? $date->format('F d, Y') : $value;
};
$dateRangeLabel = $formatDate($startDate);
if ($startDate !== $endDate) {
    $dateRangeLabel .= ' to ' . $formatDate($endDate);
}
$generatedDate = (new DateTimeImmutable('now', new DateTimeZone('Asia/Manila')))->format('F d, Y H:i:s A');
$generatedBy = trim((string) ($_SESSION['user']['fullname'] ?? ($_SESSION['user']['full_name'] ?? '')));
if ($generatedBy === '') {
    $generatedBy = trim((string) ($_SESSION['user']['firstname'] ?? '') . ' ' . (string) ($_SESSION['user']['lastname'] ?? ''));
}
if ($generatedBy === '') {
    $generatedBy = trim((string) ($_SESSION['user']['username'] ?? 'Unknown User'));
}
$logoPath = __DIR__ . '/../../assets/ml.png';
$logoHtml = is_file($logoPath)
    ? '<div class="report-logo-wrap"><img class="report-logo" src="data:image/png;base64,' . base64_encode((string) file_get_contents($logoPath)) . '" alt="Company Logo"></div>'
    : '';
$metaHtml = '<table class="report-meta"><tbody>'
    . '<tr><th>Corporate Partner:</th><td>' . $escape($partner) . '</td></tr>'
    . '<tr><th>Date:</th><td>' . $escape($dateRangeLabel) . '</td></tr>'
    . '<tr><th>Generated Date:</th><td>' . $escape($generatedDate) . '</td></tr>'
    . '<tr><th>Generated By:</th><td>' . $escape($generatedBy) . '</td></tr>'
    . '</tbody></table>';

$monthlyRows = [];
foreach ($rows as $row) {
    if (!is_array($row)) continue;
    $date = reconDaycardLocksNormalizeDate((string) ($row['transaction_date'] ?? ''));
    if ($date === '') continue;
    $status = strtolower(trim((string) ($row['status'] ?? '')));
    $statusLabel = $status === 'no_data' ? 'NO DATA' : strtoupper($status);
    $statusClass = $status === 'locked' ? 'locked' : ($status === 'unlocked' ? 'unlocked' : 'no-data');
    $monthKey = substr($date, 0, 7);
    if (!isset($monthlyRows[$monthKey])) {
        $monthlyRows[$monthKey] = ['html' => '', 'locked' => 0, 'unlocked' => 0, 'no_data' => 0, 'total' => 0];
    }
    $monthlyRows[$monthKey]['html'] .= '<tr><td>' . $escape($formatDate($date)) . '</td><td><span class="status ' . $statusClass . '">' . $escape($statusLabel) . '</span></td></tr>';
    if (isset($monthlyRows[$monthKey][$status])) $monthlyRows[$monthKey][$status]++;
    $monthlyRows[$monthKey]['total']++;
}

$reportPages = '';
$pageIndex = 0;
foreach ($monthlyRows as $monthKey => $monthData) {
    $monthDate = DateTimeImmutable::createFromFormat('!Y-m', $monthKey);
    $monthLabel = $monthDate ? $monthDate->format('F Y') : $monthKey;
    $reportPages .= '<section class="month-page' . ($pageIndex > 0 ? ' next-page' : '') . '">'
        . $logoHtml
        . $metaHtml
        . '<h1>Transaction Lock Report</h1>'
        . '<h2>' . $escape(strtoupper($partner . ' - ' . $monthLabel)) . '</h2>'
        . '<table class="report-results"><thead><tr><th>Transaction Date</th><th>Status</th></tr></thead><tbody>' . $monthData['html'] . '</tbody></table>'
        . '</section>';
    $pageIndex++;
}

if ($reportPages === '') {
    $reportPages = '<section class="month-page">' . $logoHtml . $metaHtml
        . '<h1>Transaction Lock Report</h1>'
        . '<table><tbody><tr><td colspan="2">No results found.</td></tr></tbody></table></section>';
}

$html = '<!doctype html><html><head><meta charset="UTF-8"><style>
body{font-family:DejaVu Sans,sans-serif;color:#0f172a;font-size:10px}.report-logo-wrap{text-align:center;margin:0 0 22px}.report-logo{display:inline-block;width:360px;height:auto}h1{font-size:18px;margin:0 0 12px;text-align:center}h2{font-size:13px;margin:0 0 8px;text-align:center}.report-meta{width:auto;margin:0 0 14px;border-collapse:collapse;color:#475569}.report-meta th,.report-meta td{padding:0 5px 3px 0;border:0;background:transparent;font-size:10px;text-align:left}.report-meta th{font-weight:700;white-space:nowrap}.next-page{page-break-before:always}table{width:100%;border-collapse:collapse}th,td{padding:8px;border:1px solid #dbe3ef;text-align:left}th{background:#f8fafc;font-size:9px}.report-results th,.report-results td{text-align:center}.summary-table{width:255px;margin:22px 0 0;border-collapse:collapse;page-break-inside:avoid}.summary-table th,.summary-table td{padding:4px 7px;border:1px solid #94a3b8;font-size:9px}.summary-table thead th{text-align:center;background:#f8fafc;font-weight:700}.summary-table tbody th{width:70%;background:#fff;font-weight:700}.summary-table tbody td{text-align:center}.status{font-weight:700;font-size:8px;padding:3px 7px;border-radius:10px}.locked{background:#ecfdf5;color:#047857}.unlocked{background:#fef3c7;color:#b45309}.no-data{background:#fff1f2;color:#be123c}
</style></head><body>' . $reportPages . '</body></html>';

$options = new Options();
$options->set('isRemoteEnabled', false);
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html, 'UTF-8');
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

$filename = 'transaction-lock-' . preg_replace('/[^a-z0-9]+/i', '-', strtolower($partner)) . '-' . $startDate . '-to-' . $endDate . '.pdf';
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="' . $filename . '"');
echo $dompdf->output();
