<?php

declare(strict_types=1);

require_once __DIR__ . '/../../../../../../vendor/autoload.php';
require_once __DIR__ . '/../../../../../config/session.php';

use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

function moneygram_summary_amount(array $row, string $key): array
{
    $value = $row[$key] ?? [];
    return is_array($value) ? $value : [];
}

function moneygram_summary_num(array $group, string $key): float
{
    return (float) ($group[$key] ?? 0);
}

function moneygram_summary_count(array $group): int
{
    return (int) ($group['volume'] ?? 0);
}

function moneygram_summary_generated_by(): string
{
    bootSecureSession();

    $user = isset($_SESSION['user']) && is_array($_SESSION['user']) ? $_SESSION['user'] : [];
    $fullName = trim((string) ($user['firstname'] ?? '') . ' ' . (string) ($user['lastname'] ?? ''));

    if ($fullName !== '') {
        return $fullName;
    }

    return trim((string) ($user['username'] ?? ''));
}

function moneygram_summary_fetch_data(string $startDate, string $endDate): array
{
    $oldGet = $_GET;
    $_GET = [
        'partner' => 'MONEYGRAM',
        'start_date' => $startDate,
        'end_date' => $endDate,
    ];

    ob_start();
    require __DIR__ . '/../../../../../controllers/excelcontrol/summary-report.php';
    $json = ob_get_clean();
    $_GET = $oldGet;

    $data = json_decode((string) $json, true);
    if (!is_array($data) || empty($data['success'])) {
        $message = is_array($data) && isset($data['error']) ? (string) $data['error'] : 'Unable to prepare MoneyGram summary data.';
        throw new RuntimeException($message);
    }

    return $data;
}

function moneygram_summary_month_range(string $month): array
{
    if (!preg_match('/^\d{4}-\d{2}$/', $month)) {
        throw new InvalidArgumentException('Month is required.');
    }

    $start = DateTime::createFromFormat('!Y-m-d', $month . '-01');
    if (!$start) {
        throw new InvalidArgumentException('Invalid month.');
    }

    $end = clone $start;
    $end->modify('last day of this month');

    return [$start->format('Y-m-d'), $end->format('Y-m-d'), strtoupper($start->format('F Y'))];
}

function moneygram_summary_date_label(string $date): string
{
    $dateObj = DateTime::createFromFormat('Y-m-d', $date);
    return $dateObj ? strtoupper($dateObj->format('M d, Y')) : $date;
}

function moneygram_summary_set_headers(Worksheet $sheet, string $title, string $currencyLabel, string $reportMonth, string $generatedDate, string $generatedBy, int $lastColumn): void
{
    $sheet->setCellValue('A1', 'MLHUILLIER PHILIPPINES');
    $sheet->setCellValue('A2', 'CORPORATE DEPARTMENT');
    $sheet->setCellValue('A3', 'SUMMARY REPORT');
    $sheet->setCellValue('A4', $title);
    $sheet->setCellValue('A5', $currencyLabel);
    $sheet->setCellValue('A7', 'Generated Date:');
    $sheet->setCellValue('B7', $generatedDate);
    $sheet->setCellValue('C7', 'Report Date:');
    $sheet->setCellValue('D7', $reportMonth);
    $sheet->setCellValue('A8', 'Generated By:');
    $sheet->setCellValue('B8', $generatedBy);

    $sheet->getStyle('A1:A5')->getFont()->setBold(false);
    $sheet->getStyle('A7:D8')->getFont()->setBold(false);
    $sheet->freezePane('A12');
    for ($column = 1; $column <= $lastColumn; $column++) {
        $sheet->getColumnDimension(Coordinate::stringFromColumnIndex($column))->setWidth($column === 1 ? 18 : 12);
    }
}

function moneygram_summary_style_table(Worksheet $sheet, int $lastColumn, int $lastRow): void
{
    $lastLetter = Coordinate::stringFromColumnIndex($lastColumn);
    $sheet->getStyle("A10:{$lastLetter}11")->getFont()->setBold(true);
    $sheet->getStyle("A10:{$lastLetter}11")->getAlignment()
        ->setHorizontal(Alignment::HORIZONTAL_CENTER)
        ->setVertical(Alignment::VERTICAL_CENTER);
    $sheet->getStyle("A10:{$lastLetter}{$lastRow}")->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);
    $sheet->getStyle("A10:{$lastLetter}11")->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFFFFFFF');
    $sheet->getStyle("B12:{$lastLetter}{$lastRow}")->getNumberFormat()->setFormatCode('#,##0.00');
    $sheet->getStyle("A{$lastRow}:{$lastLetter}{$lastRow}")->getFont()->setBold(false);
    $sheet->getStyle("A{$lastRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
}

function moneygram_summary_set_group_headers(Worksheet $sheet, array $groups): void
{
    $column = 1;
    foreach ($groups as $group) {
        $span = (int) $group['span'];
        $start = Coordinate::stringFromColumnIndex($column);
        $end = Coordinate::stringFromColumnIndex($column + $span - 1);
        $sheet->mergeCells("{$start}10:{$end}10");
        $sheet->setCellValue("{$start}10", (string) $group['label']);
        $column += $span;
    }
}

function moneygram_summary_write_values(Worksheet $sheet, int $rowNumber, array $values): void
{
    foreach (array_values($values) as $index => $value) {
        $cell = Coordinate::stringFromColumnIndex($index + 1) . $rowNumber;
        $sheet->setCellValue($cell, $value);
    }
}

function moneygram_summary_sum_row(Worksheet $sheet, int $rowNumber, int $firstDataRow, int $lastDataRow, int $lastColumn): void
{
    $sheet->setCellValue("A{$rowNumber}", 'Grand Total:');
    for ($column = 2; $column <= $lastColumn; $column++) {
        $letter = Coordinate::stringFromColumnIndex($column);
        $sheet->setCellValue("{$letter}{$rowNumber}", "=SUM({$letter}{$firstDataRow}:{$letter}{$lastDataRow})");
    }
}

function moneygram_summary_create_payout_sheet(Spreadsheet $spreadsheet, string $sheetTitle, array $report, string $currency, string $reportMonth, string $generatedDate, string $generatedBy, bool $firstSheet): void
{
    $sheet = $firstSheet ? $spreadsheet->getActiveSheet() : $spreadsheet->createSheet();
    $sheet->setTitle($sheetTitle);
    $lastColumn = 25;
    moneygram_summary_set_headers($sheet, 'MONEYGRAM PAYOUT', $currency . ' Transactions', $reportMonth, $generatedDate, $generatedBy, $lastColumn);
    moneygram_summary_set_group_headers($sheet, [
        ['label' => 'DATE', 'span' => 1],
        ['label' => 'MONEYGRAM', 'span' => 4],
        ['label' => 'RRC', 'span' => 4],
        ['label' => 'NET TRXNS(MONEYGRAM)', 'span' => 3],
        ['label' => 'KPX', 'span' => 3],
        ['label' => 'CANCELLED', 'span' => 4],
        ['label' => 'KPX NET', 'span' => 3],
        ['label' => 'MONEYGRAM VS. KPX VARIANCE', 'span' => 3],
    ]);
    moneygram_summary_write_values($sheet, 11, [
        '', 'Count', 'Principal', 'FX', 'Commission',
        'Count', 'Principal', 'FX', 'Commission',
        'Count', 'Principal', 'Commission',
        'Count', 'Principal', 'CHARGE',
        'Count', 'Principal', 'FX', 'Commission',
        'Count', 'Principal', 'Commission',
        'Count', 'Principal', 'Commission',
    ]);

    $rowNumber = 12;
    foreach (($report['rows'] ?? []) as $row) {
        $partner = moneygram_summary_amount($row, 'partner');
        $web = moneygram_summary_amount($row, 'web');
        $netWeb = moneygram_summary_amount($row, 'net_web');
        $variance = moneygram_summary_amount($row, 'variance');
        moneygram_summary_write_values($sheet, $rowNumber, [
            moneygram_summary_date_label((string) ($row['date'] ?? '')),
            moneygram_summary_count($partner), moneygram_summary_num($partner, 'principal'), moneygram_summary_num($partner, 'fx'), moneygram_summary_num($partner, 'commission'),
            '', '', '', '',
            moneygram_summary_count($partner), moneygram_summary_num($partner, 'principal'), moneygram_summary_num($partner, 'commission'),
            moneygram_summary_count($web), moneygram_summary_num($web, 'principal'), '',
            '', '', '', '',
            moneygram_summary_count($netWeb), moneygram_summary_num($netWeb, 'principal'), moneygram_summary_num($netWeb, 'commission'),
            moneygram_summary_count($variance), moneygram_summary_num($variance, 'principal'), moneygram_summary_num($variance, 'commission'),
        ]);
        $rowNumber++;
    }

    $totalRow = $rowNumber + 1;
    moneygram_summary_sum_row($sheet, $totalRow, 12, max(12, $rowNumber - 1), $lastColumn);
    moneygram_summary_style_table($sheet, $lastColumn, $totalRow);
}

function moneygram_summary_settlement(array $sendoutRow, array $payoutRow): array
{
    $sendoutPartner = moneygram_summary_amount($sendoutRow, 'partner');
    $sendoutVariance = moneygram_summary_amount($sendoutRow, 'variance');
    $payoutPartner = moneygram_summary_amount($payoutRow, 'partner');
    $count = moneygram_summary_count($payoutPartner) + moneygram_summary_count($sendoutPartner);
    $amount = moneygram_summary_num($payoutPartner, 'principal') - moneygram_summary_num($sendoutPartner, 'principal') + moneygram_summary_num($sendoutVariance, 'commission');

    return ['count' => $count, 'amount' => $amount];
}

function moneygram_summary_create_sendout_sheet(Spreadsheet $spreadsheet, string $sheetTitle, array $report, array $payoutReport, string $currency, string $reportMonth, string $generatedDate, string $generatedBy): void
{
    $sheet = $spreadsheet->createSheet();
    $sheet->setTitle($sheetTitle);
    $lastColumn = 29;
    moneygram_summary_set_headers($sheet, 'MONEYGRAM SENDOUT', $currency . ' Transactions', $reportMonth, $generatedDate, $generatedBy, $lastColumn);
    moneygram_summary_set_group_headers($sheet, [
        ['label' => 'DATE', 'span' => 1],
        ['label' => $currency === 'USD' ? 'GROSS' : 'MONEYGRAM', 'span' => 4],
        ['label' => 'REFUND', 'span' => 4],
        ['label' => 'NET TRXNS(MONEYGRAM)', 'span' => 3],
        ['label' => 'KPX', 'span' => 3],
        ['label' => 'CANCELLED', 'span' => 4],
        ['label' => 'KPX NET', 'span' => 3],
        ['label' => 'MONEYGRAM VS. KPX VARIANCE', 'span' => 4],
        ['label' => 'MONEYGRAM SETTLEMENT', 'span' => 3],
    ]);
    moneygram_summary_write_values($sheet, 11, [
        '', 'Count', 'Principal', 'FX', 'Commission',
        'Count', 'Principal', 'FX', 'Commission',
        'Count', 'Principal', 'Commission',
        'Count', 'Principal', 'CHARGE',
        'Count', 'Principal', 'FX', 'Commission',
        'Count', 'Principal', 'Commission',
        'Count', 'Principal', 'Commission', 'fee',
        'Count', 'Amount', 'Variance',
    ]);

    $payoutRowsByDate = [];
    foreach (($payoutReport['rows'] ?? []) as $payoutRow) {
        if (!empty($payoutRow['date'])) {
            $payoutRowsByDate[(string) $payoutRow['date']] = $payoutRow;
        }
    }

    $rowNumber = 12;
    foreach (($report['rows'] ?? []) as $row) {
        $date = (string) ($row['date'] ?? '');
        $partner = moneygram_summary_amount($row, 'partner');
        $refund = moneygram_summary_amount($row, 'refund');
        $netPartner = isset($row['net_partner']) && is_array($row['net_partner']) ? $row['net_partner'] : $partner;
        $web = moneygram_summary_amount($row, 'web');
        $cancelled = moneygram_summary_amount($row, 'cancelled');
        $netWeb = moneygram_summary_amount($row, 'net_web');
        $variance = moneygram_summary_amount($row, 'variance');
        $settlement = moneygram_summary_settlement($row, $payoutRowsByDate[$date] ?? []);

        moneygram_summary_write_values($sheet, $rowNumber, [
            moneygram_summary_date_label($date),
            moneygram_summary_count($partner), moneygram_summary_num($partner, 'principal'), moneygram_summary_num($partner, 'fx'), moneygram_summary_num($partner, 'commission'),
            moneygram_summary_count($refund), moneygram_summary_num($refund, 'principal'), moneygram_summary_num($refund, 'fx'), moneygram_summary_num($refund, 'commission'),
            moneygram_summary_count($netPartner), moneygram_summary_num($netPartner, 'principal'), moneygram_summary_num($netPartner, 'commission'),
            moneygram_summary_count($web), moneygram_summary_num($web, 'principal'), moneygram_summary_num($web, 'commission'),
            moneygram_summary_count($cancelled), moneygram_summary_num($cancelled, 'principal'), moneygram_summary_num($cancelled, 'fx'), moneygram_summary_num($cancelled, 'commission'),
            moneygram_summary_count($netWeb), moneygram_summary_num($netWeb, 'principal'), moneygram_summary_num($netWeb, 'commission'),
            moneygram_summary_count($variance), moneygram_summary_num($variance, 'principal'), moneygram_summary_num($variance, 'commission'), moneygram_summary_num($web, 'commission'),
            $settlement['count'], -$settlement['amount'], $settlement['amount'],
        ]);
        $rowNumber++;
    }

    $totalRow = $rowNumber + 1;
    moneygram_summary_sum_row($sheet, $totalRow, 12, max(12, $rowNumber - 1), $lastColumn);
    moneygram_summary_style_table($sheet, $lastColumn, $totalRow);
}

try {
    $month = trim((string) ($_GET['month'] ?? ''));
    [$startDate, $endDate, $reportMonth] = moneygram_summary_month_range($month);
    $data = moneygram_summary_fetch_data($startDate, $endDate);

    $spreadsheet = new Spreadsheet();
    $spreadsheet->getProperties()
        ->setCreator('ML Auto Recon')
        ->setTitle('MoneyGram Summary Report');

    $payoutReports = $data['currency_reports'] ?? [];
    $sendoutReports = $data['sendout_reports'] ?? [];
    $generatedDate = date('M d, Y h:i A');
    $generatedBy = moneygram_summary_generated_by();

    moneygram_summary_create_payout_sheet($spreadsheet, 'PAYOUT PHP', $payoutReports['php'] ?? [], 'PHP', $reportMonth, $generatedDate, $generatedBy, true);
    moneygram_summary_create_payout_sheet($spreadsheet, 'PAYOUT USD', $payoutReports['usd'] ?? [], 'USD', $reportMonth, $generatedDate, $generatedBy, false);
    moneygram_summary_create_sendout_sheet($spreadsheet, 'SENDOUT PHP', $sendoutReports['php'] ?? [], $payoutReports['php'] ?? [], 'PHP', $reportMonth, $generatedDate, $generatedBy);
    moneygram_summary_create_sendout_sheet($spreadsheet, 'SENDOUT USD', $sendoutReports['usd'] ?? [], $payoutReports['usd'] ?? [], 'USD', $reportMonth, $generatedDate, $generatedBy);
    $spreadsheet->setActiveSheetIndex(0);

    $filename = 'MONEYGRAM_SUMMARY_REPORT_' . str_replace('-', '_', $month) . '.xlsx';
    if (ob_get_length()) {
        ob_end_clean();
    }
    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: max-age=0');

    $writer = new Xlsx($spreadsheet);
    $writer->save('php://output');
    exit;
} catch (Throwable $e) {
    if (ob_get_length()) {
        ob_end_clean();
    }
    http_response_code(500);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode(['success' => false, 'error' => $e->getMessage()]);
    exit;
}
