<?php

declare(strict_types=1);

require_once __DIR__ . '/../../../../../../vendor/autoload.php';
require_once __DIR__ . '/../../../../../config/session.php';

use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

const MONEYGRAM_SUMMARY_SECTION_HEADER_ROW = 10;
const MONEYGRAM_SUMMARY_GROUP_HEADER_ROW = 11;
const MONEYGRAM_SUMMARY_COLUMN_HEADER_ROW = 12;
const MONEYGRAM_SUMMARY_FIRST_DATA_ROW = 13;

function moneygram_summary_amount(array $row, string $key): array
{
    $value = $row[$key] ?? [];
    return is_array($value) ? $value : [];
}

function moneygram_summary_num(array $group, string $key): float
{
    return (float) ($group[$key] ?? 0);
}

function moneygram_summary_count(array $group): int
{
    return (int) ($group['volume'] ?? 0);
}

function moneygram_summary_generated_by(): string
{
    bootSecureSession();

    $user = isset($_SESSION['user']) && is_array($_SESSION['user']) ? $_SESSION['user'] : [];
    $fullName = trim((string) ($user['firstname'] ?? '') . ' ' . (string) ($user['lastname'] ?? ''));

    if ($fullName !== '') {
        return $fullName;
    }

    return trim((string) ($user['username'] ?? ''));
}

function moneygram_summary_fetch_data(string $startDate, string $endDate): array
{
    $oldGet = $_GET;
    $_GET = [
        'partner' => 'MONEYGRAM',
        'start_date' => $startDate,
        'end_date' => $endDate,
    ];

    ob_start();
    require __DIR__ . '/../../../../../controllers/excelcontrol/summary-report.php';
    $json = ob_get_clean();
    $_GET = $oldGet;

    $data = json_decode((string) $json, true);
    if (!is_array($data) || empty($data['success'])) {
        $message = is_array($data) && isset($data['error']) ? (string) $data['error'] : 'Unable to prepare MoneyGram summary data.';
        throw new RuntimeException($message);
    }

    return $data;
}

function moneygram_summary_month_range(string $month): array
{
    if (!preg_match('/^\d{4}-\d{2}$/', $month)) {
        throw new InvalidArgumentException('Month is required.');
    }

    $start = DateTime::createFromFormat('!Y-m-d', $month . '-01');
    if (!$start) {
        throw new InvalidArgumentException('Invalid month.');
    }

    $end = clone $start;
    $end->modify('last day of this month');

    return [$start->format('Y-m-d'), $end->format('Y-m-d'), strtoupper($start->format('F Y'))];
}

function moneygram_summary_date_label(string $date): string
{
    $dateObj = DateTime::createFromFormat('Y-m-d', $date);
    return $dateObj ? strtoupper($dateObj->format('M d, Y')) : $date;
}

function moneygram_summary_set_headers(Worksheet $sheet, string $title, string $currencyLabel, string $reportMonth, string $generatedDate, string $generatedBy, int $lastColumn): void
{
    $sheet->setCellValue('A1', 'MLHUILLIER PHILIPPINES');
    $sheet->setCellValue('A2', 'RECONCILIATION AND VARIANCE REPORT');
    $sheet->setCellValue('A3', $title);
    $sheet->setCellValue('A4', $currencyLabel);
    $sheet->setCellValue('A6', 'Transaction Date:');
    $sheet->setCellValue('B6', $reportMonth);
    $sheet->setCellValue('A7', 'Generated Date:');
    $sheet->setCellValue('B7', $generatedDate);
    $sheet->setCellValue('A8', 'Generated By:');
    $sheet->setCellValue('B8', $generatedBy);

    $sheet->getStyle('A1:A8')->getFont()->setBold(false);
    $sheet->freezePane('A' . MONEYGRAM_SUMMARY_FIRST_DATA_ROW);
    for ($column = 1; $column <= $lastColumn; $column++) {
        $sheet->getColumnDimension(Coordinate::stringFromColumnIndex($column))->setWidth($column === 1 ? 18 : 12);
    }
}

function moneygram_summary_style_table(Worksheet $sheet, int $lastColumn, int $lastRow, array $countColumns): void
{
    $lastLetter = Coordinate::stringFromColumnIndex($lastColumn);
    $sectionHeaderRow = MONEYGRAM_SUMMARY_SECTION_HEADER_ROW;
    $groupHeaderRow = MONEYGRAM_SUMMARY_GROUP_HEADER_ROW;
    $columnHeaderRow = MONEYGRAM_SUMMARY_COLUMN_HEADER_ROW;
    $firstDataRow = MONEYGRAM_SUMMARY_FIRST_DATA_ROW;
    $sheet->getStyle("A{$sectionHeaderRow}:{$lastLetter}{$columnHeaderRow}")->getFont()->setBold(true);
    $sheet->getStyle("A{$sectionHeaderRow}:{$lastLetter}{$columnHeaderRow}")->getAlignment()
        ->setHorizontal(Alignment::HORIZONTAL_CENTER)
        ->setVertical(Alignment::VERTICAL_CENTER);
    $sheet->getStyle("A{$sectionHeaderRow}:{$lastLetter}{$lastRow}")->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);
    $sheet->getStyle("A{$sectionHeaderRow}:{$lastLetter}{$columnHeaderRow}")->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FFFFFFFF');
    $sheet->getStyle("B{$firstDataRow}:{$lastLetter}{$lastRow}")->getNumberFormat()->setFormatCode('#,##0.00');
    foreach ($countColumns as $column) {
        $sheet->getStyle("{$column}{$firstDataRow}:{$column}{$lastRow}")->getNumberFormat()->setFormatCode('#,##0');
    }
    $sheet->getStyle("A{$lastRow}:{$lastLetter}{$lastRow}")->getFont()->setBold(false);
    $sheet->getStyle("A{$lastRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
}

function moneygram_summary_set_group_headers(Worksheet $sheet, array $groups, int $startColumn = 1): void
{
    $column = $startColumn;
    foreach ($groups as $group) {
        $span = (int) $group['span'];
        $start = Coordinate::stringFromColumnIndex($column);
        $end = Coordinate::stringFromColumnIndex($column + $span - 1);
        $rowspan = (int) ($group['rowspan'] ?? 1);
        $endRow = $rowspan > 1 ? MONEYGRAM_SUMMARY_COLUMN_HEADER_ROW : MONEYGRAM_SUMMARY_GROUP_HEADER_ROW;
        $sheet->mergeCells("{$start}" . MONEYGRAM_SUMMARY_GROUP_HEADER_ROW . ":{$end}{$endRow}");
        $sheet->setCellValue($start . MONEYGRAM_SUMMARY_GROUP_HEADER_ROW, (string) $group['label']);
        $column += $span;
    }
}

function moneygram_summary_set_section_headers(Worksheet $sheet, array $sections): void
{
    $column = 1;
    foreach ($sections as $section) {
        $span = (int) $section['span'];
        $start = Coordinate::stringFromColumnIndex($column);
        $end = Coordinate::stringFromColumnIndex($column + $span - 1);
        $rowspan = (int) ($section['rowspan'] ?? 1);
        $endRow = MONEYGRAM_SUMMARY_SECTION_HEADER_ROW + max(1, $rowspan) - 1;
        $sheet->mergeCells("{$start}" . MONEYGRAM_SUMMARY_SECTION_HEADER_ROW . ":{$end}{$endRow}");
        $sheet->setCellValue($start . MONEYGRAM_SUMMARY_SECTION_HEADER_ROW, (string) $section['label']);
        $column += $span;
    }
}

function moneygram_summary_net_rev_share(array $partner, array $cancelled): float
{
    return moneygram_summary_num($partner, 'fx') - moneygram_summary_num($cancelled, 'fx');
}

function moneygram_summary_write_values(Worksheet $sheet, int $rowNumber, array $values, int $startColumn = 1): void
{
    foreach (array_values($values) as $index => $value) {
        $cell = Coordinate::stringFromColumnIndex($index + $startColumn) . $rowNumber;
        $sheet->setCellValue($cell, $value);
    }
}

function moneygram_summary_sum_row(Worksheet $sheet, int $rowNumber, int $firstDataRow, int $lastDataRow, int $lastColumn): void
{
    $sheet->setCellValue("A{$rowNumber}", 'Grand Total:');
    for ($column = 2; $column <= $lastColumn; $column++) {
        $letter = Coordinate::stringFromColumnIndex($column);
        $sheet->setCellValue("{$letter}{$rowNumber}", "=SUM({$letter}{$firstDataRow}:{$letter}{$lastDataRow})");
    }
}

function moneygram_summary_create_payout_sheet(Spreadsheet $spreadsheet, string $sheetTitle, array $report, string $currency, string $reportMonth, string $generatedDate, string $generatedBy, bool $firstSheet): void
{
    $sheet = $firstSheet ? $spreadsheet->getActiveSheet() : $spreadsheet->createSheet();
    $sheet->setTitle($sheetTitle);
    $lastColumn = 23;
    moneygram_summary_set_headers($sheet, 'MONEYGRAM PAYOUT', 'CURRENCY ' . $currency, $reportMonth, $generatedDate, $generatedBy, $lastColumn);
    moneygram_summary_set_section_headers($sheet, [
        ['label' => 'DATE', 'span' => 1, 'rowspan' => 3],
        ['label' => 'Partner Data', 'span' => 12],
        ['label' => 'KPX Web Data', 'span' => 7],
        ['label' => 'VARIANCE', 'span' => 3],
    ]);
    moneygram_summary_set_group_headers($sheet, [
        ['label' => 'MONEYGRAM', 'span' => 4],
        ['label' => 'CANCELLED', 'span' => 4],
        ['label' => 'NET', 'span' => 4],
        ['label' => 'KPX', 'span' => 3],
        ['label' => 'CANCELLED', 'span' => 4],
        ['label' => 'MONEYGRAM vs KPX WEB', 'span' => 3],
    ], 2);
    moneygram_summary_write_values($sheet, MONEYGRAM_SUMMARY_COLUMN_HEADER_ROW, [
        'Volume', 'Principal', 'Rev Share', 'Comm',
        'Volume', 'Principal', 'Rev Share', 'Comm',
        'Volume', 'Principal', 'Rev Share', 'Comm',
        'Volume', 'Principal', 'CHARGE',
        'Volume', 'Principal', 'Rev Share', 'Comm',
        'Volume', 'Principal', 'Comm',
    ], 2);

    $rowNumber = MONEYGRAM_SUMMARY_FIRST_DATA_ROW;
    foreach (($report['rows'] ?? []) as $row) {
        $partner = moneygram_summary_amount($row, 'partner');
        $cancelled = moneygram_summary_amount($row, 'partner_cancelled');
        $netPartner = moneygram_summary_amount($row, 'net_partner');
        $web = moneygram_summary_amount($row, 'web');
        $variance = moneygram_summary_amount($row, 'variance');
        moneygram_summary_write_values($sheet, $rowNumber, [
            moneygram_summary_date_label((string) ($row['date'] ?? '')),
            moneygram_summary_count($partner), moneygram_summary_num($partner, 'principal'), moneygram_summary_num($partner, 'fx'), moneygram_summary_num($partner, 'commission'),
            moneygram_summary_count($cancelled), moneygram_summary_num($cancelled, 'principal'), moneygram_summary_num($cancelled, 'fx'), moneygram_summary_num($cancelled, 'commission'),
            moneygram_summary_count($netPartner), moneygram_summary_num($netPartner, 'principal'), moneygram_summary_num($netPartner, 'fx'), moneygram_summary_num($netPartner, 'commission'),
            moneygram_summary_count($web), moneygram_summary_num($web, 'principal'), '',
            '', '', '', '',
            moneygram_summary_count($variance), moneygram_summary_num($variance, 'principal'), moneygram_summary_num($variance, 'commission'),
        ]);
        $rowNumber++;
    }

    $totalRow = $rowNumber + 1;
    moneygram_summary_sum_row($sheet, $totalRow, MONEYGRAM_SUMMARY_FIRST_DATA_ROW, max(MONEYGRAM_SUMMARY_FIRST_DATA_ROW, $rowNumber - 1), $lastColumn);
    moneygram_summary_style_table($sheet, $lastColumn, $totalRow, ['B', 'F', 'J', 'N', 'Q', 'U']);
}

function moneygram_summary_settlement(array $sendoutRow, array $payoutRow): array
{
    $sendoutPartner = moneygram_summary_amount($sendoutRow, 'partner');
    $sendoutCancelled = moneygram_summary_amount($sendoutRow, 'partner_cancelled');
    $sendoutNetPartner = moneygram_summary_amount($sendoutRow, 'net_partner');
    $payoutPartner = moneygram_summary_amount($payoutRow, 'partner');
    $payoutNetPartner = moneygram_summary_amount($payoutRow, 'net_partner');
    $count = moneygram_summary_count($payoutPartner) + moneygram_summary_count($sendoutPartner);
    $amount = moneygram_summary_num($sendoutPartner, 'principal')
        + moneygram_summary_num($sendoutPartner, 'fee')
        - moneygram_summary_num($sendoutNetPartner, 'commission')
        - moneygram_summary_num($payoutNetPartner, 'principal')
        - moneygram_summary_num($sendoutCancelled, 'principal');

    return ['count' => $count, 'amount' => $amount, 'variance' => -$amount];
}

function moneygram_summary_create_sendout_sheet(Spreadsheet $spreadsheet, string $sheetTitle, array $report, array $payoutReport, string $currency, string $reportMonth, string $generatedDate, string $generatedBy): void
{
    $sheet = $spreadsheet->createSheet();
    $sheet->setTitle($sheetTitle);
    $lastColumn = 27;
    moneygram_summary_set_headers($sheet, 'MONEYGRAM SENDOUT', 'CURRENCY ' . $currency, $reportMonth, $generatedDate, $generatedBy, $lastColumn);
    moneygram_summary_set_section_headers($sheet, [
        ['label' => 'DATE', 'span' => 1, 'rowspan' => 3],
        ['label' => 'Partner Data', 'span' => 12],
        ['label' => 'KPX Web Data', 'span' => 7],
        ['label' => 'VARIANCE', 'span' => 4],
        ['label' => 'MONEYGRAM SETTLEMENT', 'span' => 3, 'rowspan' => 2],
    ]);
    moneygram_summary_set_group_headers($sheet, [
        ['label' => $currency === 'USD' ? 'GROSS' : 'MONEYGRAM', 'span' => 4],
        ['label' => 'CANCELLED', 'span' => 4],
        ['label' => 'NET', 'span' => 4],
        ['label' => 'KPX', 'span' => 3],
        ['label' => 'CANCELLED', 'span' => 4],
        ['label' => 'MONEYGRAM vs KPX WEB', 'span' => 4],
    ], 2);
    moneygram_summary_write_values($sheet, MONEYGRAM_SUMMARY_COLUMN_HEADER_ROW, [
        'Volume', 'Principal', 'Rev Share', 'Comm',
        'Volume', 'Principal', 'Rev Share', 'Comm',
        'Volume', 'Principal', 'Rev Share', 'Comm',
        'Volume', 'Principal', 'CHARGE',
        'Volume', 'Principal', 'Rev Share', 'Comm',
        'Volume', 'Principal', 'Comm', 'fee',
        'Volume', 'Amount', 'Variance',
    ], 2);

    $payoutRowsByDate = [];
    foreach (($payoutReport['rows'] ?? []) as $payoutRow) {
        if (!empty($payoutRow['date'])) {
            $payoutRowsByDate[(string) $payoutRow['date']] = $payoutRow;
        }
    }

    $rowNumber = MONEYGRAM_SUMMARY_FIRST_DATA_ROW;
    foreach (($report['rows'] ?? []) as $row) {
        $date = (string) ($row['date'] ?? '');
        $partner = moneygram_summary_amount($row, 'partner');
        $refund = moneygram_summary_amount($row, 'partner_cancelled');
        $netPartner = isset($row['net_partner']) && is_array($row['net_partner']) ? $row['net_partner'] : $partner;
        $web = moneygram_summary_amount($row, 'web');
        $cancelled = moneygram_summary_amount($row, 'cancelled');
        $variance = moneygram_summary_amount($row, 'variance');
        $settlement = moneygram_summary_settlement($row, $payoutRowsByDate[$date] ?? []);
        $varianceComm = moneygram_summary_num($netPartner, 'commission') - moneygram_summary_num($web, 'commission');
        $varianceFee = moneygram_summary_num($partner, 'fee');

        moneygram_summary_write_values($sheet, $rowNumber, [
            moneygram_summary_date_label($date),
            moneygram_summary_count($partner), moneygram_summary_num($partner, 'principal'), moneygram_summary_num($partner, 'fx'), moneygram_summary_num($partner, 'commission'),
            moneygram_summary_count($refund), moneygram_summary_num($refund, 'principal'), moneygram_summary_num($refund, 'fx'), moneygram_summary_num($refund, 'commission'),
            moneygram_summary_count($netPartner), moneygram_summary_num($netPartner, 'principal'), moneygram_summary_net_rev_share($partner, $refund), moneygram_summary_num($netPartner, 'commission'),
            moneygram_summary_count($web), moneygram_summary_num($web, 'principal'), moneygram_summary_num($web, 'commission'),
            moneygram_summary_count($cancelled), moneygram_summary_num($cancelled, 'principal'), moneygram_summary_num($cancelled, 'fx'), moneygram_summary_num($cancelled, 'commission'),
            moneygram_summary_count($variance), moneygram_summary_num($variance, 'principal'), $varianceComm, $varianceFee,
            $settlement['count'], $settlement['amount'], $settlement['variance'],
        ]);
        $rowNumber++;
    }

    $totalRow = $rowNumber + 1;
    moneygram_summary_sum_row($sheet, $totalRow, MONEYGRAM_SUMMARY_FIRST_DATA_ROW, max(MONEYGRAM_SUMMARY_FIRST_DATA_ROW, $rowNumber - 1), $lastColumn);
    moneygram_summary_style_table($sheet, $lastColumn, $totalRow, ['B', 'F', 'J', 'N', 'Q', 'U', 'Y']);
}

try {
    $month = trim((string) ($_GET['month'] ?? ''));
    [$startDate, $endDate, $reportMonth] = moneygram_summary_month_range($month);
    $data = moneygram_summary_fetch_data($startDate, $endDate);

    $spreadsheet = new Spreadsheet();
    $spreadsheet->getProperties()
        ->setCreator('ML Auto Recon')
        ->setTitle('MoneyGram Summary Report');

    $payoutReports = $data['currency_reports'] ?? [];
    $sendoutReports = $data['sendout_reports'] ?? [];
    $generatedDate = (new DateTimeImmutable('now', new DateTimeZone('Asia/Manila')))->format('F d, Y h:i A');
    $generatedBy = moneygram_summary_generated_by();

    moneygram_summary_create_payout_sheet($spreadsheet, 'PAYOUT PHP', $payoutReports['php'] ?? [], 'PHP', $reportMonth, $generatedDate, $generatedBy, true);
    moneygram_summary_create_payout_sheet($spreadsheet, 'PAYOUT USD', $payoutReports['usd'] ?? [], 'USD', $reportMonth, $generatedDate, $generatedBy, false);
    moneygram_summary_create_sendout_sheet($spreadsheet, 'SENDOUT PHP', $sendoutReports['php'] ?? [], $payoutReports['php'] ?? [], 'PHP', $reportMonth, $generatedDate, $generatedBy);
    moneygram_summary_create_sendout_sheet($spreadsheet, 'SENDOUT USD', $sendoutReports['usd'] ?? [], $payoutReports['usd'] ?? [], 'USD', $reportMonth, $generatedDate, $generatedBy);
    $spreadsheet->setActiveSheetIndex(0);

    $filename = 'MONEYGRAM_RECON-&-VARIANCE_SUMMARY_REPORT_' . str_replace('-', '_', $month) . '.xlsx';
    if (ob_get_length()) {
        ob_end_clean();
    }
    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: max-age=0');

    $writer = new Xlsx($spreadsheet);
    $writer->save('php://output');
    exit;
} catch (Throwable $e) {
    if (ob_get_length()) {
        ob_end_clean();
    }
    http_response_code(500);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode(['success' => false, 'error' => $e->getMessage()]);
    exit;
}
