<?php

declare(strict_types=1);

require_once __DIR__ . '/../../../../../../vendor/autoload.php';
require_once __DIR__ . '/../../../../../config/session.php';

use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

function wic_summary_group(array $row, string $key): array
{
    return isset($row[$key]) && is_array($row[$key]) ? $row[$key] : [];
}

function wic_summary_num(array $group, string $key): float
{
    return (float) ($group[$key] ?? 0);
}

function wic_summary_count(array $group): int
{
    return (int) ($group['volume'] ?? 0);
}

function wic_summary_generated_by(): string
{
    bootSecureSession();
    $user = isset($_SESSION['user']) && is_array($_SESSION['user']) ? $_SESSION['user'] : [];
    $name = trim((string) ($user['firstname'] ?? '') . ' ' . (string) ($user['lastname'] ?? ''));
    return $name !== '' ? $name : trim((string) ($user['username'] ?? ''));
}

function wic_summary_month_range(string $month): array
{
    if (!preg_match('/^\d{4}-\d{2}$/', $month)) {
        throw new InvalidArgumentException('Month is required.');
    }
    $start = DateTime::createFromFormat('!Y-m-d', $month . '-01');
    if (!$start) {
        throw new InvalidArgumentException('Invalid month.');
    }
    $end = clone $start;
    $end->modify('last day of this month');
    return [$start->format('Y-m-d'), $end->format('Y-m-d'), strtoupper($start->format('F Y'))];
}

function wic_summary_fetch_data(string $startDate, string $endDate): array
{
    $oldGet = $_GET;
    $_GET = ['partner' => 'WORLDCOM INTERNATIONAL COMMUNICATIONS', 'start_date' => $startDate, 'end_date' => $endDate];
    ob_start();
    require __DIR__ . '/../../../../../controllers/excelcontrol/summary-report.php';
    $json = ob_get_clean();
    $_GET = $oldGet;
    $data = json_decode((string) $json, true);
    if (!is_array($data) || empty($data['success'])) {
        throw new RuntimeException((string) ($data['error'] ?? 'Unable to prepare WIC summary data.'));
    }
    return $data;
}

function wic_summary_date_label(string $date): string
{
    $dateObj = DateTime::createFromFormat('Y-m-d', $date);
    return $dateObj ? strtoupper($dateObj->format('M d, Y')) : $date;
}

function wic_summary_write_values(Worksheet $sheet, int $rowNumber, array $values): void
{
    foreach (array_values($values) as $index => $value) {
        $sheet->setCellValue(Coordinate::stringFromColumnIndex($index + 1) . $rowNumber, $value);
    }
}

function wic_summary_build_sheet(Spreadsheet $spreadsheet, string $title, array $report, string $reportMonth, string $generatedDate, string $generatedBy, bool $firstSheet): void
{
    $sheet = $firstSheet ? $spreadsheet->getActiveSheet() : $spreadsheet->createSheet();
    $sheet->setTitle($title);
    $sheet->setCellValue('A1', 'MLHUILLIER PHILIPPINES');
    $sheet->setCellValue('A2', 'CORPORATE DEPARTMENT');
    $sheet->setCellValue('A3', 'SUMMARY REPORT');
    $sheet->setCellValue('A4', $title);
    $sheet->setCellValue('A7', 'Generated Date:');
    $sheet->setCellValue('B7', $generatedDate);
    $sheet->setCellValue('C7', 'Report Date:');
    $sheet->setCellValue('D7', $reportMonth);
    $sheet->setCellValue('A8', 'Generated By:');
    $sheet->setCellValue('B8', $generatedBy);

    $groups = [
        ['', 1], [$title, 2], ['WEB KPX', 3], ['NET WEB REPORT', 3], ['PARTNER VS. WEB', 3],
    ];
    $column = 1;
    foreach ($groups as [$label, $span]) {
        $start = Coordinate::stringFromColumnIndex($column);
        $end = Coordinate::stringFromColumnIndex($column + $span - 1);
        $sheet->mergeCells("{$start}10:{$end}10");
        $sheet->setCellValue("{$start}10", $label);
        $column += $span;
    }
    wic_summary_write_values($sheet, 11, [
        'Date',
        'Vol', 'Principal',
        'Vol', 'Principal', 'COMMISSION',
        'Vol', 'Principal', 'COMMISSION',
        'Vol', 'Principal', 'COMMISSION',
    ]);

    $rowNumber = 12;
    foreach (($report['rows'] ?? []) as $row) {
        $partner = wic_summary_group($row, 'partner');
        $web = wic_summary_group($row, 'web');
        $netWeb = wic_summary_group($row, 'net_web');
        $variance = wic_summary_group($row, 'variance');
        wic_summary_write_values($sheet, $rowNumber, [
            wic_summary_date_label((string) ($row['date'] ?? '')),
            wic_summary_count($partner), wic_summary_num($partner, 'principal'),
            wic_summary_count($web), wic_summary_num($web, 'principal'), wic_summary_num($web, 'commission'),
            wic_summary_count($netWeb), wic_summary_num($netWeb, 'principal'), wic_summary_num($netWeb, 'commission'),
            wic_summary_count($variance), wic_summary_num($variance, 'principal'), wic_summary_num($variance, 'commission'),
        ]);
        $rowNumber++;
    }

    $totalRow = $rowNumber + 1;
    $sheet->setCellValue("A{$totalRow}", 'TOTAL');
    for ($col = 2; $col <= 12; $col++) {
        $letter = Coordinate::stringFromColumnIndex($col);
        $sheet->setCellValue("{$letter}{$totalRow}", "=SUM({$letter}12:{$letter}" . max(12, $rowNumber - 1) . ")");
    }

    $sheet->freezePane('A12');
    foreach (range(1, 12) as $col) {
        $sheet->getColumnDimension(Coordinate::stringFromColumnIndex($col))->setWidth($col === 1 ? 18 : 12);
    }
    $sheet->getStyle('A10:L11')->getFont()->setBold(true);
    $sheet->getStyle('A10:L11')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER)->setVertical(Alignment::VERTICAL_CENTER);
    $sheet->getStyle("A10:L{$totalRow}")->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);
    $sheet->getStyle("B12:L{$totalRow}")->getNumberFormat()->setFormatCode('#,##0.00');
}

try {
    [$startDate, $endDate, $reportMonth] = wic_summary_month_range(trim((string) ($_GET['month'] ?? '')));
    $data = wic_summary_fetch_data($startDate, $endDate);
    $spreadsheet = new Spreadsheet();
    $reports = $data['currency_reports'] ?? [];
    $generatedDate = date('M d, Y h:i A');
    $generatedBy = wic_summary_generated_by();

    wic_summary_build_sheet($spreadsheet, 'WIC PHP', $reports['php'] ?? [], $reportMonth, $generatedDate, $generatedBy, true);
    wic_summary_build_sheet($spreadsheet, 'WIC USD', $reports['usd'] ?? [], $reportMonth, $generatedDate, $generatedBy, false);
    $spreadsheet->setActiveSheetIndex(0);

    $filename = 'WIC_SUMMARY_REPORT_' . str_replace('-', '_', (string) ($_GET['month'] ?? '')) . '.xlsx';
    if (ob_get_length()) ob_end_clean();
    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: max-age=0');
    (new Xlsx($spreadsheet))->save('php://output');
    exit;
} catch (Throwable $e) {
    if (ob_get_length()) ob_end_clean();
    http_response_code(500);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode(['success' => false, 'error' => $e->getMessage()]);
    exit;
}
