<?php

declare(strict_types=1);

require_once __DIR__ . '/../../../../../../vendor/autoload.php';
require_once __DIR__ . '/../../../../../config/session.php';

use PhpOffice\PhpSpreadsheet\Cell\Coordinate;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

function mbtc_summary_group(array $row, string $key): array
{
    return isset($row[$key]) && is_array($row[$key]) ? $row[$key] : [];
}

function mbtc_summary_num(array $group, string $key): float
{
    return (float) ($group[$key] ?? 0);
}

function mbtc_summary_count(array $group): int
{
    return (int) ($group['volume'] ?? 0);
}

function mbtc_summary_generated_by(): string
{
    bootSecureSession();
    $user = isset($_SESSION['user']) && is_array($_SESSION['user']) ? $_SESSION['user'] : [];
    $name = trim((string) ($user['firstname'] ?? '') . ' ' . (string) ($user['lastname'] ?? ''));
    return $name !== '' ? $name : trim((string) ($user['username'] ?? ''));
}

function mbtc_summary_month_range(string $month): array
{
    if (!preg_match('/^\d{4}-\d{2}$/', $month)) {
        throw new InvalidArgumentException('Month is required.');
    }
    $start = DateTime::createFromFormat('!Y-m-d', $month . '-01');
    if (!$start) {
        throw new InvalidArgumentException('Invalid month.');
    }
    $end = clone $start;
    $end->modify('last day of this month');
    return [$start->format('Y-m-d'), $end->format('Y-m-d'), strtoupper($start->format('F Y'))];
}

function mbtc_summary_fetch_data(string $startDate, string $endDate): array
{
    $oldGet = $_GET;
    $_GET = ['partner' => 'METROBANK HEAD OFFICE', 'start_date' => $startDate, 'end_date' => $endDate];
    ob_start();
    require __DIR__ . '/../../../../../controllers/excelcontrol/summary-report.php';
    $json = ob_get_clean();
    $_GET = $oldGet;
    $data = json_decode((string) $json, true);
    if (!is_array($data) || empty($data['success'])) {
        throw new RuntimeException((string) ($data['error'] ?? 'Unable to prepare MBTC summary data.'));
    }
    return $data;
}

function mbtc_summary_date_label(string $date): string
{
    $dateObj = DateTime::createFromFormat('Y-m-d', $date);
    return $dateObj ? strtoupper($dateObj->format('M d, Y')) : $date;
}

function mbtc_summary_deposit_values(array $source, array $deposit): array
{
    $principal = mbtc_summary_num($source, 'principal');
    $commission = mbtc_summary_num($source, 'commission');
    $commissionShare = $commission / 56;
    $commissionNet = $commission - $commissionShare;
    $debit = (float) ($deposit['debit'] ?? 0);
    $credit = (float) ($deposit['credit'] ?? 0);
    return [
        'debit' => $debit,
        'credit' => $credit,
        'variance' => $debit + $credit - $principal - $commissionNet,
        'commission_share' => $commissionShare,
        'commission_net' => $commissionNet,
    ];
}

function mbtc_summary_write_values(Worksheet $sheet, int $rowNumber, array $values): void
{
    foreach (array_values($values) as $index => $value) {
        $sheet->setCellValue(Coordinate::stringFromColumnIndex($index + 1) . $rowNumber, $value);
    }
}

try {
    [$startDate, $endDate, $reportMonth] = mbtc_summary_month_range(trim((string) ($_GET['month'] ?? '')));
    $data = mbtc_summary_fetch_data($startDate, $endDate);
    $spreadsheet = new Spreadsheet();
    $sheet = $spreadsheet->getActiveSheet();
    $sheet->setTitle('MBTC');

    $sheet->setCellValue('A1', 'MLHUILLIER PHILIPPINES');
    $sheet->setCellValue('A2', 'CORPORATE DEPARTMENT');
    $sheet->setCellValue('A3', 'SUMMARY REPORT');
    $sheet->setCellValue('A4', 'MBTC');
    $sheet->setCellValue('A7', 'Generated Date:');
    $sheet->setCellValue('B7', date('M d, Y h:i A'));
    $sheet->setCellValue('C7', 'Report Date:');
    $sheet->setCellValue('D7', $reportMonth);
    $sheet->setCellValue('A8', 'Generated By:');
    $sheet->setCellValue('B8', mbtc_summary_generated_by());

    $groups = [
        ['', 1], ['MBTC', 3], ['WEB KPX', 3], ['DUPLICATE TRXNS', 3], ['NET WEB REPORT', 3],
        ['PARTNER VS. WEB', 3], ['DEPOSIT VS. WEB', 3], ['', 2],
    ];
    $column = 1;
    foreach ($groups as [$label, $span]) {
        $start = Coordinate::stringFromColumnIndex($column);
        $end = Coordinate::stringFromColumnIndex($column + $span - 1);
        $sheet->mergeCells("{$start}10:{$end}10");
        $sheet->setCellValue("{$start}10", $label);
        $column += $span;
    }
    mbtc_summary_write_values($sheet, 11, [
        'Date',
        'Vol', 'Principal', 'COMMISSION',
        'Vol', 'Principal', 'COMMISSION',
        'Vol', 'Principal', 'COMMISSION',
        'Vol', 'Principal', 'COMMISSION',
        'Vol', 'Principal', 'COMMISSION',
        'DEBIT', 'CREDIT', 'VARIANCE',
        '', '',
    ]);

    $rowNumber = 12;
    foreach (($data['rows'] ?? []) as $row) {
        $partner = mbtc_summary_group($row, 'partner');
        $web = mbtc_summary_group($row, 'web');
        $duplicates = mbtc_summary_group($row, 'duplicates');
        $netWeb = mbtc_summary_group($row, 'net_web');
        $variance = mbtc_summary_group($row, 'variance');
        $deposit = mbtc_summary_deposit_values($netWeb, isset($row['deposit']) && is_array($row['deposit']) ? $row['deposit'] : []);
        mbtc_summary_write_values($sheet, $rowNumber, [
            mbtc_summary_date_label((string) ($row['date'] ?? '')),
            mbtc_summary_count($partner), mbtc_summary_num($partner, 'principal'), mbtc_summary_num($partner, 'commission'),
            mbtc_summary_count($web), mbtc_summary_num($web, 'principal'), mbtc_summary_num($web, 'commission'),
            mbtc_summary_count($duplicates), mbtc_summary_num($duplicates, 'principal'), mbtc_summary_num($duplicates, 'commission'),
            mbtc_summary_count($netWeb), mbtc_summary_num($netWeb, 'principal'), mbtc_summary_num($netWeb, 'commission'),
            mbtc_summary_count($variance), mbtc_summary_num($variance, 'principal'), mbtc_summary_num($variance, 'commission'),
            $deposit['debit'], $deposit['credit'], $deposit['variance'], $deposit['commission_share'], $deposit['commission_net'],
        ]);
        $rowNumber++;
    }

    $totalRow = $rowNumber + 1;
    $sheet->setCellValue("A{$totalRow}", 'TOTAL');
    for ($col = 2; $col <= 21; $col++) {
        $letter = Coordinate::stringFromColumnIndex($col);
        $sheet->setCellValue("{$letter}{$totalRow}", "=SUM({$letter}12:{$letter}" . max(12, $rowNumber - 1) . ")");
    }

    $sheet->freezePane('A12');
    foreach (range(1, 21) as $col) {
        $sheet->getColumnDimension(Coordinate::stringFromColumnIndex($col))->setWidth($col === 1 ? 18 : 12);
    }
    $sheet->getStyle("A10:U11")->getFont()->setBold(true);
    $sheet->getStyle("A10:U11")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER)->setVertical(Alignment::VERTICAL_CENTER);
    $sheet->getStyle("A10:U{$totalRow}")->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);
    $sheet->getStyle("B12:U{$totalRow}")->getNumberFormat()->setFormatCode('#,##0.00');

    $filename = 'MBTC_SUMMARY_REPORT_' . str_replace('-', '_', (string) ($_GET['month'] ?? '')) . '.xlsx';
    if (ob_get_length()) ob_end_clean();
    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: max-age=0');
    (new Xlsx($spreadsheet))->save('php://output');
    exit;
} catch (Throwable $e) {
    if (ob_get_length()) ob_end_clean();
    http_response_code(500);
    header('Content-Type: application/json; charset=utf-8');
    echo json_encode(['success' => false, 'error' => $e->getMessage()]);
    exit;
}
